# Generated by Django 5.1 on 2024-09-10 21:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="course",
        ),
        migrations.RemoveField(
            model_name="like",
            name="trainer",
        ),
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
