# Generated by Django 5.1.1 on 2024-09-20 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_remove_like_course_remove_like_trainer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
