# Generated by Django 5.1 on 2024-08-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(default="This course has no description for now"),
            preserve_default=False,
        ),
    ]
