# Generated by Django 5.1.1 on 2024-09-12 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_course_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course_comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.student"
            ),
        ),
    ]
