# Generated by Django 5.1.1 on 2024-09-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_course_comment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="profile_picture",
            field=models.ImageField(
                default="static/assets/img/mylogo.png", upload_to="static/students"
            ),
        ),
    ]
