# Generated by Django 5.1.1 on 2024-09-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_reply"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reply",
            name="comment",
        ),
        migrations.AddField(
            model_name="course_comment",
            name="replies",
            field=models.ManyToManyField(blank=True, to="accounts.reply"),
        ),
    ]
