# Generated by Django 5.0.4 on 2024-06-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=255)),
                ("Subject", models.CharField(max_length=255)),
                ("Email", models.EmailField(max_length=255)),
                ("Message", models.CharField(max_length=500)),
                ("date_created", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FirstName", models.CharField(max_length=50)),
                ("LastName", models.CharField(max_length=50)),
                ("UserName", models.CharField(max_length=50)),
                ("Email", models.EmailField(max_length=255)),
                ("password", models.CharField(max_length=500)),
                ("date_created", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Email", models.EmailField(max_length=255)),
            ],
        ),
    ]
