# Generated by Django 5.0.4 on 2024-06-11 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="date_created",
            field=models.DateTimeField(verbose_name=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="registration",
            name="date_created",
            field=models.DateTimeField(verbose_name=datetime.datetime.now),
        ),
    ]
