# Generated by Django 5.0.4 on 2024-07-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="cover_photo",
            field=models.ImageField(upload_to="static/img/"),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="passport_photo",
            field=models.ImageField(upload_to="static/img/"),
        ),
    ]
