# Generated by Django 5.0.4 on 2024-06-11 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu", "0002_alter_contact_date_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="date_created",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="registration",
            name="date_created",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
