# Generated by Django 5.0.4 on 2024-06-13 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edu", "0003_alter_contact_date_created_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Registration",
        ),
    ]
