# Generated by Django 5.0.4 on 2024-08-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edu", "0004_remove_student_courses_alter_student_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="courses",
        ),
        migrations.RemoveField(
            model_name="student",
            name="user",
        ),
        migrations.RemoveField(
            model_name="trainer",
            name="user",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.DeleteModel(
            name="Trainer",
        ),
    ]
